name: Test github actions

on:
 push:
  tags:
    - 'v*'
    
 workflow_dispatch:

jobs:
  get_metadata:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker meta
       id: meta
       uses: docker/metadata-action@v3
       with:
         images: name/app
   

  test:
    runs-on: ubuntu-latest
    needs: [get_metadata]
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: |
          tg=$(echo ${GITHUB_REF#refs/*/} | cut -b 2-)
          echo ::set-output name=tag::$tg
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          SUPER_SECRET: ${{ secrets.SUPER_SECRET}}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          echo ${{github.ref}}
          echo 'Tags output'
          echo ${{ needs.get_metadata.meta.tags }}
  
  test_if:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print test
        run: echo "on main"
  
  test_if_develop:
    needs: [test]
    if:  github.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print test
        run: echo "on develop"
        
  test_reusable_action:
   needs: [test]
   uses: pklimov-vivy/test-actions/.github/workflows/reusable_action.yaml@main
   with:
     username: test
   secrets:
     token: "123"
        
   
