name: Test github actions

on:
 push:
  branches:
    - main
    - develop
 workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: |
          tg=$(echo ${GITHUB_REF#refs/*/} | cut -b 2-)
          echo ::set-output name=tag::$tg
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          SUPER_SECRET: ${{ secrets.SUPER_SECRET}}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          echo ${{github.ref}}
  
  test_if:
    needs: [test]
    if: github.ref == 'ref/head/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: print test
        run: echo "on main"
  
  test_if_develop:
    needs: [test]
    if:  github.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: print test
        run: echo "on develop"
        
   
